apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: calico
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  # disable kindnet, so we can install our own CNI once cluster is created
  disableDefaultCNI: true
  # set the pod subnet
  podSubnet: "192.168.0.0/16"
